### ISSUE TITLE
local sphinx builds broken

### ISSUE THREAD

**Issue by wikfeldt** [coderefinery/testing#109]
something in 40b02ad1d032cdad1207c82d46bfa142d1685d42 broke my local sphinx, even though it seems to look fine on gh-pages. 

Locally I get
```
...
reading sources... [ 45%] gitlab-ci
Exception occurred:
  File "/Users/ktw/miniconda3/lib/python3.8/site-packages/sphinx/util/__init__.py", line 441, in parselinenos
    parts = spec.split(',')
AttributeError: 'int' object has no attribute 'split'
```

**Comment by rkdarst** [comment]
With a new venv, it works for me (current default branch).  If you
recreate the venv and also `make clean`, does it still fail?

I have Sphinx==3.4.3 after re-install

**Comment by wikfeldt** [comment]
yep, a fresh install works now!
