### ISSUE TITLE
C++ testing

### ISSUE THREAD

**Issue by robertodr** [coderefinery/testing#110]
- [X] Refactor/clean up Google Test example. https://github.com/bast/gtest-demo/pull/10
- [x] Add Catch2 example. https://github.com/ENCCS/catch2-demo
- [x] Add Boost.Test example. https://github.com/ENCCS/boost-test-demo
- [x] Add C++ tab in the "Test design" episode.
~- [ ] Maybe: dynamic analysis tools.~
~- [ ] Maybe: use of sanitizers.~

**Comment by PoojanSmart** [comment]
Hey, I have added cpp code to `test-design.md` file. Please review and merge.

**Comment by robertodr** [comment]
- [ ] Translate pure-impure functions solution to C++.
- [ ] Translate FizzBuzz example to C++.
- [ ] Translate randomness example to C++. Wait on #132 to be merged.

**Comment by PoojanSmart** [comment]
can you link files to be updated?
