### ISSUE TITLE
Remove commit hooks from testing episode

### ISSUE THREAD

**Issue by JensWehner** [coderefinery/testing#111]
at the netherlands escience center we taught this episode multiple times and we think the local automated testing using commit hooks should be removed for the following reasons:

- Commit hooks are a git feature and are much more general than just running tests. We see that teaching the hooks here somehow sets up a connection in the student's mind between git and testing, which does not exist.
- From a developers perspective especially on larger projects this is a horrible workflow, because it discourages people from committing often, because the tests run each time. Also modern IDEs make running tests easy already, so there is no reason to use a githook. Especially today they are good reasons to commit/push even if tests fail. 
- Especially with the prevalence of CI today, it is just not needed anymore. 
- We feel speaking more about test design and focus on the CI is simply a much better use of time.

**Comment by bast** [comment]
I agree. I never use local hooks in "normal" work and this was placed there more for pedagogical reasons than for practical reasons and given that the time is always precious, I think we should refocus it to test design.

**Comment by bast** [comment]
Done in #113.
