### ISSUE TITLE
add several optional exercises to Test design episode

### ISSUE THREAD

**Issue by wikfeldt** [coderefinery/testing#117]
The idea is to have one main unit testing exercise with multiple functions/classes/code snippets that tests should be written for. This main exercise could also be split into multiple main exercises.

But it would be good to have additional exercises on other topics and we can collect ideas (and external resources) in this issue.
Some ideas:
- testing randomness
- integration test 
- testing IO (should probably be one of the main exercises)

**Comment by wikfeldt** [comment]
we should try to have these optional exercises in as many different languages as possible but each type of exercise probably doesn't need to be replicated in each language

**Comment by bast** [comment]
- randomness is there
- I/O is there but needs to be clearer
- I will add end-to-end

**Comment by bast** [comment]
Followed-up in #150.
