### ISSUE TITLE
add examples in R, Julia, C/C++, Fortran and Octave/Matlab to Motivation episode

### ISSUE THREAD

**Issue by wikfeldt** [coderefinery/testing#119]
simply need to translate the different version of the `fahrenheit_to_celsius` function in https://coderefinery.github.io/testing/motivation/

**Comment by PoojanSmart** [comment]
to be added in `motivation.md` file right?

**Comment by wikfeldt** [comment]
correct!

**Comment by PoojanSmart** [comment]
hey, I added the code for cpp but it was rejected by some process. Sorry for that. I am new to github. can you tell me what was the mistake?

**Comment by wikfeldt** [comment]
thanks for contributing! Did you try to push directly to this repository? Only CodeRefinery staff have write access here, what you would need to do is to fork the repository, clone to your computer, commit your changes on a new branch, push to your fork, and from your fork's webpage create a pull request to this repository. A walk-through of this process is in the CodeRefinery collaborative Git lesson: https://coderefinery.github.io/git-collaborative/

**Comment by PoojanSmart** [comment]
I did that. created new branch after forking. changed it and crated a pull request but it shows error after adding pull request. just adding a tab for c/c++ also causes error. 
![image](https://user-images.githubusercontent.com/44301271/109101432-af778e80-774c-11eb-8d07-25bdef170348.png)
![image](https://user-images.githubusercontent.com/44301271/109101462-c0280480-774c-11eb-9771-c62ba7339148.png)

**Comment by wikfeldt** [comment]
@PoojanSmart if you change the `c/c++` tabs to simply `c++` then this will work with Sphinx. If you just just to the same branch it will get appended to this pull request. When we have that we can merge!

**Comment by wikfeldt** [comment]
@wmvanvliet thanks a lot for contributing the R exercises. Since we're very short on instructors fluent in R I'll have to ask you: would you be able to add R snippets to the [motivation episode](https://coderefinery.github.io/testing/motivation/)? it's hopefully very little work

**Comment by wmvanvliet** [comment]
#125

**Comment by bast** [comment]
Can we close this and turn it to smaller follow-up issues since most of it is done?

**Comment by wikfeldt** [comment]
absolutely, closing
