### ISSUE TITLE
merge gitlab-ci and github-actions episodes into one

### ISSUE THREAD

**Issue by wikfeldt** [coderefinery/testing#124]
for compactness and clarity and to avoid future divergences

**Comment by wikfeldt** [comment]
doesn't look like sphinx-tabs supports rendering markdown in any simple way inside group-tabs, so i'm putting this on ice at the moment. Unless @rkdarst has any ideas!

**Comment by bast** [comment]
I am looking into this. I will take the issue if my initial tests are fruitful.

**Comment by bast** [comment]
I think this will work. Taking.
