### ISSUE TITLE
Mention that the factorial function might overflow and/or exceed recursion depth

### ISSUE THREAD

**Issue by robertodr** [coderefinery/testing#134]
The implementation of the factorial we ask to test can run into trouble with large-ish values of the input parameter:
- either because of integer overflow
- exceed recursion depth.

Solving both is beyond the scope of the workshop (using the Gamma function and double precision) but these points could be useful for discussion in the breakout rooms.

I am changing the C++ implementation to use `unsigned int`, such that passing negative numbers will be caught as an error at compile-time, rather than run-time. @wikfeldt I believe the same can be done for Julia (by using `UInt` in place of `Int`) and I would argue that's a better approach to show in a code example.

**Comment by johanhellsvik** [comment]
Good points on integer overflow and recursion depth. I agree that these can be interesting to bring up for discussion in the breakout rooms.

**Comment by bast** [comment]
I recommend that:
- We mention this with one sentence as discussion topic.
  This will help also instructors of future workshops. We don't have to say more.
- The Uint/Int suggestion is moved to a separate issue so that these can be solved independently.

**Comment by wikfeldt** [comment]
@robertodr using UInt would be cumbersome in Julia because input integer arguments would need to be explicitly converted, and i think the recommended practice is to instead assert non-negativity
