### ISSUE TITLE
Try to use literalinclude for "test design"

### ISSUE THREAD

**Issue by bast** [coderefinery/testing#153]
The episode file is impossibly long and difficult to handle and read and also test.

It would be better to keep the files outside and include them into the lesson text.

**Comment by bast** [comment]
I won't fix this for the current workshop though.

**Comment by bast** [comment]
This would also give us back code highlighting when writing the episode.

**Comment by wikfeldt** [comment]
i'm not sure how to do literalinclude in markdown. Tried a couple of things like using `{eval-rst}` blocks (from MyST) etc but nothing worked. So i'll convert test-design.md to RST, and maybe the other episodes too. 

I also find RST nicer for more complicated stuff like nested blocks when the number of back-tics in markdown becomes hard to write and read

**Comment by rkdarst** [comment]
In theory any Sphinx directive can work in MyST, they are
"sphinx/docutils directives" which either the ReST or MyST parser
should be able to use, with slightly different syntax.  Did you try
this?

**Comment by wikfeldt** [comment]
i'm not sure i tried this, do you have an example? i've started converting though, and i don't think i'm doing any future lesson developer a disfavor by converting to rst. Or what do you think?

**Comment by rkdarst** [comment]
I think like this:

``````

```{literalinclude} example.py
:language: ruby
:emphasize-lines: 12,15-18
:linenos:
```

``````

This should be the MyST equivalent of this:
  https://www.sphinx-doc.org/en/master/usage/restructuredtext/directives.html#directive-literalinclude
(but I have not tested this myself...)

**Comment by wikfeldt** [comment]
nah doesn't work locally at least, with `myst_nb` installed. The code block simply renders the "{literalinclude} example.py" string

**Comment by rkdarst** [comment]
I got it to work here:

https://coderefinery.github.io/sphinx-lesson/branch/rkdarst--sample-episode-md/sample-episode-md/
https://raw.githubusercontent.com/coderefinery/sphinx-lesson/rkdarst/sample-episode-md/content/sample-episode-md.md


myst_nb should pull in myst_parser.  Anyway, that sample site only has
`sphinx_lesson` as a dependency, which pulls in myst_nb, which pulls
in myst_parser.  Are versions up to date?

**Comment by wikfeldt** [comment]
i tried upgrading sphinx-lesson, myst-nb and myst-parser. The latter two were bumped from 0.11.1 and 0.13.2 to 0.12.0 and 0.13.6, respectively. But it still doesn't render correctly. I guess the problem is that it's heavily nested? I have:
```
\``````{challenge} 1. Function that receives a number and returns a number
\`````{tabs}
   \````{code-tab} py
   \```{literalinclude} factorial.py
   :language: python
   :emphasize-lines: 1-5
   :linenos:
   \```
   \````
...
```

**Comment by bast** [comment]
I haven't tested this but maybe "normal" tab and not code tab? Maybe code tab is incompatible with literalinclude.

**Comment by wikfeldt** [comment]
good idea, but alas no...

**Comment by bast** [comment]
I will also test something quick ...

**Comment by bast** [comment]
Seems to work for me: https://gist.github.com/bast/5d915ff293640a89364697afcdc323ca

**Comment by wikfeldt** [comment]
thanks for testing this! It now works for me, the culprit was a missing newline! 😤

So this doesn't work:
```
``````{challenge} 1. Function that receives a number and returns a number
  `````{tabs}
    ````{tab} py
      \```{literalinclude} code/factorial.py
      :language: python
      :emphasize-lines: 1-5
      :linenos:
      \```
```

but this does:
```
``````{challenge} 1. Function that receives a number and returns a number
  `````{tabs}
    ````{tab} py

      \```{literalinclude} code/factorial.py
      :language: python
      :emphasize-lines: 1-5
      :linenos:
      \```
```

not very nice behaviour!

**Comment by bast** [comment]
Somehow the tabs seem to always eat the first line. I noticed this by trying simple text and then the first line disappeared.
