### ISSUE TITLE
when this lesson is taught standalone, CI should be moved last

### ISSUE THREAD

**Issue by wikfeldt** [coderefinery/testing#162]
the test-design episode should be main focus and come right after testing-locally when this is taught without git-intro and git-collab preceding it
Add this to instructor guide

**Comment by dianaiusan** [comment]
Good idea. Also, some were overwhelmed by the large number of exercises. Some people have a problem choosing if they have too many exercises to choose from. Maybe we could add some as optional. Should have probably been a new issue (bad practice here.)
