### ISSUE TITLE
consider developing alternative version of CI episode without pull requests

### ISSUE THREAD

**Issue by wikfeldt** [coderefinery/testing#164]
when the lesson is taught standalone it doesn't make as much sense to include forking, raising issues and sending PRs. The CI episode can have a standalone version focusing only on setting up automated tests

**Comment by dianaiusan** [comment]
Yes, one could keep just steps 1-6 of this section. One could add the solution with all the Git commands as well so that the newcomers to Git do not get stuck.

**Comment by rkdarst** [comment]
+1, I use CI more often on small repos without PRs, and it is still
useful there.  But then again, most repos are small without PRs...
