### ISSUE TITLE
important: coloring in tabbed code cells is messed up

### ISSUE THREAD

**Issue by wikfeldt** [coderefinery/testing#187]
... in my browser at least.

Here for example: https://coderefinery.org/testing/motivation/#testing-in-a-nutshell
This is what it looks like for me:
<img width="651" alt="Screenshot 2022-03-28 at 16 26 01" src="https://user-images.githubusercontent.com/10846818/160420159-737074dc-c5a0-4c6b-a8fe-b0c9d09e5c11.png">

**Comment by wikfeldt** [comment]
yep, problem only with dark theme enabled

**Comment by rkdarst** [comment]
It is not a problem in sphinx-tabs upstream: https://sphinx-tabs.readthedocs.io/en/latest/
... so I wonder what we do.  Could it be a sphinx_rtd_theme version issue?  I will investigate some

**Comment by rkdarst** [comment]
https://github.com/executablebooks/sphinx-tabs/issues/152

sphinx-tabs 3.3.1 (released 10 days ago) fixes it.  My hypothesis is that the cache action is storing the old version 3.3.0.  Investigating.

**Comment by rkdarst** [comment]
Github Pages doesn't seem to be deploying.  I guess we wait some and either rebuild or naturally send some PRs and see if it works.

**Comment by johanhellsvik** [comment]
On Firefox it looks good now using dark theme or light theme, as well as when using default theme.

**Comment by wikfeldt** [comment]
yes, problem solved now!

**Comment by bast** [comment]
Can we close?

**Comment by johanhellsvik** [comment]
Things look good now. We can close.
