### ISSUE TITLE
More exercise for the pytest local episode

### ISSUE THREAD

**Issue by rkdarst** [coderefinery/testing#193]
Feedback from 2022-09 was that this was very fast and there was too much time.  We weren't in a rush for the rest, and making it much faster might make it hard for those who are slower.

I suggest adding some advanced exercises to that episode.  For example
- `--pdb` (and anything else that helps with TDD)
- Test-driven development (add test first, then add code to make it pass)
- Running only certain tests with `-k`
- Fixtures (maybe too advanced/would take too long for anyone who doesn't know it already)
- Not capturing stdout with `-s` (this may be too esoteric but it's one of the things I use often when developing)

**Comment by tpfau** [comment]
We actually plan to mostly skip the local testing exercises in favor for having more time and an actual (not type along) exercise for the CI setup and automated testing. i.e. letting participants set up their own small repo with tests (or rather setting up a repo without workflows that contains a few tests and have them add a new test for a function.

**Comment by bast** [comment]
I would rather combine exercises into one block. That episode really misses R examples (#165) and other languages before we add more Python features.
