### ISSUE TITLE
Build workflow is broken

### ISSUE THREAD

**Issue by bast** [coderefinery/testing#194]
https://github.com/coderefinery/testing/blob/main/requirements.txt#L4

It seems something got removed/merged? @rkdarst

**Comment by rkdarst** [comment]
It has been built and deployed.

Medium-term, we should remove the custom sphinx-copybutton install path.  But, rather than changing now and changing after it is released, we can leave it as it is now (not broken) and then remove the custom path on next release.

**Comment by bast** [comment]
Weird. I got an email from GitHub and it looked like that branch did not exist anymore. Maybe it was just a dream. Sorry for the noise.

**Comment by rkdarst** [comment]
no, you are right, that is exactly what happened.  And you needed to tell me so I could add that branch back on my personal fork of sphinx-copybutton (and then I re-ran the workflow) and it passed.

Either I didn't realize the implications of deleting the branch and did it myself, or the repository that merged my PR could delete the branch in my own repository.

**Comment by bast** [comment]
Ah OK :-)
