### ISSUE TITLE
Is a package missing to do coverage?

### ISSUE THREAD

**Issue by bast** [coderefinery/testing#200]
https://github.com/coderefinery/software/blob/main/environment.yml

**Comment by bast** [comment]
pytest-cov ?

**Comment by rkdarst** [comment]
`pytest-cov=4.0.0` for the (now updated) environment files.  Then the following command can be run locally: `pytest --cov-report "xml:coverage.xml"  --cov=.`

The Actions file already has it explicitly.  We don't ask peolpe to run this locally, but it can be with this: `pytest --cov-report "html:coverage-report" test_functions.py --cov=.`

Should this be added to environment.yml or not?
