### ISSUE TITLE
Add links/references

### ISSUE THREAD

**Issue by bast** [coderefinery/testing#37]
Just so I don't forget - copying from chat (cheers to @blankdots): https://science.sciencemag.org/content/314/5807/1856.summary original source was here: http://archive.euroscipy.org/talk/6634

**Comment by bast** [comment]
More links:
- https://realpython.com/python-testing/
- http://pythontesting.net/start-here/

**Comment by juholehtonen** [comment]
An article about a glitch in Python code affecting >100 chemistry studies:
https://arstechnica.com/information-technology/2019/10/chemists-discover-cross-platform-python-scripts-not-so-cross-platform/
Original source: https://pubs.acs.org/doi/full/10.1021/acs.orglett.9b03216
Full article: https://drive.google.com/open?id=1kaK4NMGGDwhfDzuCWDDLUjGM5qvlZOjn (CRbase/workshops/2019/hackathon-stockholm-nov-2019/repro-hack/01-juho-python-glob-in-chemistry/)
