### ISSUE TITLE
notes from Instructor Training WS nov 2019

### ISSUE THREAD

**Issue by mehimself** [coderefinery/testing#42]
how to motivate
- what are the goals?
  - test coverage warrants confidence
- intro to linting, testing
- broken example with obscure defect
  - show how a test saves the day (cm vs. inches, imprecise pi)?
- scenarios and design patterns for various use cases (fitted with test scopes)
  - unit tests
  - parallelization tests
  - asynchronous tests
  - systems tests
  - for each applied language
- "not necessary, is investment for future"
- how to convince supervisors / end users of benefits?
- test-driven development
  - good for (re-)structuring projects
  - not suitable for developing existing projects w/o TDD
  - new WS format: hackathon
   - write tests, others implement them
   - reflect on ease of doing this and how to simplify this process (refactoring/separation of concerns)
   - nice link to modular code development

**Comment by rkdarst** [comment]
I've linked this in the instructor guide, so closing this issue.
