### ISSUE TITLE
Improve 07-travis excercise

### ISSUE THREAD

**Issue by vezeli** [coderefinery/testing#49]
Coderefinery participants learn that LICENSE is an important part of any project. This file, however, is not a part of the exercise [07-travis](https://github.com/coderefinery/testing/blob/gh-pages/_episodes/07-travis.md) only README file is.

I think that this exercise is a good educational opportunity to remind the participants about the importance of LICENSE file and show them how it works in practice. Technically, they should be able to reuse the code without a license. I would suggest adding a step where participants are expected to go to https://choosealicense.com/ and take a permissive license and add it to their git repositories.

I would be willing to make a PR for this issue if you are interested?

**Comment by bast** [comment]
Good idea! This can also be an optional step for those who finish this exercise much earlier than the rest of the classroom.

I think it could be like this:
- External contributor opens an issue asking for a license
- Maintainer adds a license and solves that issue

I think the above is more realistic compared to external contributor adding a LICENSE file as part of a pull request. Or what do you think about it?

**Comment by vezeli** [comment]
>This can also be an optional step for those who finish this exercise much earlier than the rest of the classroom.

This would mean that during the exercise the external contributor makes a PR to a project that doesn't contain LICENSE file? I am actually hoping to avoid this situation and make it more illustrative that LICENSE file is very important.

What you suggested is an option, however I suggest instead of making it optional adding an additional step between step 1. and 2.

- Maintainer clones the repository
- Maintainer adds LICENSE file
- Maintainer pushes the repository to the remote

The rest of the steps would follow as they are right now with a slight change in 3. (there is no need to clone the repository there). Tell me what you think about it?

**Comment by bast** [comment]
I am working on it ...

**Comment by bast** [comment]
I will make this an optional step. I have seen many repos without a license so I will make it optional to suggest a license to somebody else's repo.
