### ISSUE TITLE
add some optional exercises

### ISSUE THREAD

**Issue by wikfeldt** [coderefinery/testing#56]
could be interesting to some participants to have 1 or 2 somewhat more complex optional exercises in e.g. episode 4

**Comment by rkdarst** [comment]
We tried using the `--pdb` option.  This would work best with a test that raised an exception directly in the function.

**Comment by bast** [comment]
Which episode/exercise does this refer to?

**Comment by bast** [comment]
Assuming it's the GH Actions exercise. Working on it ...
