### ISSUE TITLE
Does the pre-commit exercise work on Anaconda and Windows?

### ISSUE THREAD

**Issue by bast** [coderefinery/testing#58]
The chmod part I guess does not work. And one of the participants managed to get it to work by giving it the `.bat` suffix and skipping the chmod part (?).

This part is confusing on Windows.

**Comment by bast** [comment]
From HackMD:

```
- In windows 10, anaconda prompt: The command ...\pytest-example>move pre-commit.bat  /hooks gave this output: Access is denied. 0 file(s) moved.
    - This seemed to work: move pre-commit.bat .git/hooks
```

**Comment by bast** [comment]
Depends also if Anaconda is configured to use Bash or Powershell or some other shell. We have something in the install instructions but probably not visible/clear enough.

**Comment by matuskalas** [comment]
I never had a similar problem in win, chmod works for me in both Git Bash and Anaconda Prompt, but I never needed it when writing pre-commit scripts. It looks like it gets executable somehow automatically(?) I'll do some more investigation later...
