### ISSUE TITLE
"View on GitHub" points to wrong place, something is missing in the URL

### ISSUE THREAD

**Issue by bast** [coderefinery/testing#83]

**Comment by rkdarst** [comment]
Found the problem, automatic detection of repo name now fails when it
is in the content/ directory.

I could use Github Actions environment variables to auto-detect it.  I
wonder if that would be a useful way of auto-detecting stuff?  Right
now our conf.py is basically fully automated, which is kind of nice
but a bit fragile.

**Comment by bast** [comment]
We should I think anyway move conf.py out of content (https://github.com/coderefinery/sphinx-lesson/issues/35).
