### ISSUE TITLE
git hook: windows script

### ISSUE THREAD

**Issue by rkdarst** [coderefinery/testing#91]
Is this a correct script on Windows:

````
   The script is the same for all operating systems:
   ```shell
   #!/bin/bash

   pytest example.py
   ```
````

In particular, `#!/bin/bash`

**Comment by bast** [comment]
Thanks. This is probably not right.

**Comment by matuskalas** [comment]
From my experience (Git Bash on Win 10), pre-commit hooks work the same as on other systems. They also run in my Anaconda Prompt, although there are some weird issues with their content (maybe shell issue?). I can investigate more if you want....

Btw., I had major issues with hooks when testing them in GitHub Desktop on Win, but on some other win installations they worked in GitHub Desktop, too. Annoying, but well, requesting all contributors to use git in terminal if possible.

**Comment by bast** [comment]
This issue is not relevant anymore since the local hook episode got removed in #111.
